import { Poppins } from "next/font/google";
import "@/styles/globals.scss";
import ThemeSwitch from "@/components/custom-provider/ThemeSwitch";

const inter = Poppins({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] });

export const metadata = {
  title: "4846Fess",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <ThemeSwitch> */}
        <body className={inter.className}>{children}</body>
      {/* </ThemeSwitch> */}
    </html>
  );
}
